import { existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DATA_DIR, FILES } from './paths';

// A client who cannot undo is a client who does not dare to touch anything.
// Every save keeps the version it replaced, so the answer to "I have broken
// something" is a button rather than a telephone call.

const DIR = join(DATA_DIR, 'history');
const KEEP = 30;

export type Version = { id: string; at: string; bytes: number };

export function snapshot(label: string): void {
  if (!existsSync(FILES.content)) return;
  mkdirSync(DIR, { recursive: true });
  const id = `${new Date().toISOString().replace(/[:.]/g, '-')}-${label}`;
  writeFileSync(join(DIR, `${id}.json`), readFileSync(FILES.content), { mode: 0o600 });

  // Thirty versions is months of ordinary editing and a few megabytes.
  const kept = list();
  for (const version of kept.slice(KEEP)) unlinkSync(join(DIR, `${version.id}.json`));
}

export function list(): Version[] {
  if (!existsSync(DIR)) return [];
  return readdirSync(DIR)
    .filter((name) => name.endsWith('.json'))
    .map((name) => {
      const id = name.replace(/\.json$/, '');
      const iso = id.slice(0, 24).replace(/-(\d{2})-(\d{2})-(\d{3})Z$/, ':$1:$2.$3Z');
      return {
        id,
        at: Number.isNaN(Date.parse(iso)) ? id.slice(0, 19) : iso,
        bytes: readFileSync(join(DIR, name)).byteLength,
      };
    })
    .sort((a, b) => b.id.localeCompare(a.id));
}

export function read(id: string): Record<string, unknown> | null {
  // The name is generated by this module; a request naming anything else does
  // not reach the disk.
  if (!list().some((version) => version.id === id)) return null;
  return JSON.parse(readFileSync(join(DIR, `${id}.json`), 'utf8')) as Record<string, unknown>;
}
