import { audit } from './audit';
import { MAX_BODY_BYTES } from './auth';
import { HttpError, authorizeApi, failure, type Ctx } from './authz';
import { get, run, tx, type Row } from './db';
import { delayIf, failIf } from './faults';
import { EXPORT_LIMIT, findRecord, readQuery, runList, type ModuleDef } from './list';
import { MODULES, type ModuleKey } from './matrix';
import { definition, sourceValues } from './modules';
import { issueSetupToken } from './setup';
import { parseBody } from './validate';

// The handlers behind every module endpoint. Each one runs the same order:
// session, grant, then the record's scope inside the query, then the state
// rule, then the write in a serialised transaction. Every refusal after the
// grant check is audited here; the grant refusals are audited in authz.

function moduleOf(key: string): ModuleDef {
  const def = definition(key);
  if (!def) throw new HttpError(404, 'notFound');
  return def;
}

async function readBody(request: Request): Promise<unknown> {
  const text = await request.text();
  if (text.length > MAX_BODY_BYTES) throw new HttpError(413, 'tooLarge');
  if (!text) return {};
  try {
    return JSON.parse(text);
  } catch {
    throw new HttpError(400, 'badRequest');
  }
}

function refused(ctx: Ctx | null, action: string, module: string, record: string | null, error: unknown): void {
  if (!ctx) return;
  const status = error instanceof HttpError ? error.status : 409;
  if (status === 401 || status === 403) return;
  audit({ accountId: ctx.account.id, role: ctx.role, action, module, record, outcome: 'refused', status, address: ctx.address });
}

// The public part of a row: the columns the table shows, the fields its
// actions need, and the actions this role may run on it now.
export async function list(request: Request, key: string): Promise<Response> {
  try {
    const def = moduleOf(key);
    const ctx = await authorizeApi(request, def.key, 'view');
    failIf(`list.${def.key}`);
    await delayIf(`delay.${def.key}`);
    const query = readQuery(def, new URL(request.url).searchParams);
    const result = runList(def, ctx, query);
    return Response.json({ ok: true, ...result, sort: `${query.sortKey}.${query.sortDir}`, filters: query.filters });
  } catch (error) {
    return failure(error);
  }
}

export async function detail(request: Request, key: string, id: string): Promise<Response> {
  let ctx: Ctx | null = null;
  try {
    const def = moduleOf(key);
    ctx = await authorizeApi(request, def.key, 'view');
    const item = findRecord(def, ctx, id);
    return Response.json({ ok: true, item });
  } catch (error) {
    refused(ctx, `${key}.view`, key, id, error);
    return failure(error);
  }
}

const KEY = /^[A-Za-z0-9-]{8,80}$/;

// A create carries a key generated by the client. A second request with the
// same key returns the record the first one created, so a double click or a
// retried request makes one record.
export async function create(request: Request, key: string): Promise<Response> {
  let ctx: Ctx | null = null;
  try {
    const def = moduleOf(key);
    ctx = await authorizeApi(request, def.key, 'create');
    if (!def.create) throw new HttpError(405, 'notAllowed');
    const idempotencyKey = request.headers.get('idempotency-key') ?? '';
    if (!KEY.test(idempotencyKey)) throw new HttpError(400, 'idempotencyKey');
    const body = await readBody(request);
    const values = parseBody(def.create.fields, body, sourceValues(def.create.fields));
    const current = ctx;
    const created = tx(() => {
      const previous = get('SELECT record_id, account_id, module FROM idempotency WHERE key = ?', [idempotencyKey]);
      if (previous) {
        if (Number(previous.account_id) !== current.account.id || previous.module !== def.key) {
          throw new HttpError(409, 'idempotencyKey');
        }
        return { id: Number(previous.record_id), replay: true };
      }
      const id = def.create!.run(current, values, idempotencyKey);
      run('INSERT INTO idempotency (key, account_id, module, record_id, created_at) VALUES (?, ?, ?, ?, ?)', [
        idempotencyKey,
        current.account.id,
        def.key,
        id,
        new Date().toISOString(),
      ]);
      return { id, replay: false };
    });
    if (!created.replay) {
      audit({ accountId: ctx.account.id, role: ctx.role, action: `${def.key}.create`, module: def.key, record: created.id, outcome: 'allowed', status: 201, address: ctx.address });
    }
    const item = findRecord(def, ctx, String(created.id));
    const extra: Record<string, string> = {};
    if (def.key === 'staff' && !created.replay) extra.setup = `/setup?token=${issueSetupToken(created.id)}`;
    return Response.json({ ok: true, item, replay: created.replay, ...extra }, { status: created.replay ? 200 : 201 });
  } catch (error) {
    refused(ctx, `${key}.create`, key, null, error);
    return failure(error);
  }
}

export async function update(request: Request, key: string, id: string): Promise<Response> {
  let ctx: Ctx | null = null;
  try {
    const def = moduleOf(key);
    ctx = await authorizeApi(request, def.key, 'update');
    if (!def.update) throw new HttpError(405, 'notAllowed');
    const body = await readBody(request);
    const values = parseBody(def.update.fields, body, sourceValues(def.update.fields));
    const current = ctx;
    tx(() => {
      const row = findRecord(def, current, id);
      if (def.update!.when && !def.update!.when(row)) throw new HttpError(409, 'state');
      def.update!.run(current, row, values);
    });
    audit({ accountId: ctx.account.id, role: ctx.role, action: `${def.key}.update`, module: def.key, record: id, outcome: 'allowed', status: 200, address: ctx.address });
    return Response.json({ ok: true, item: findRecord(def, ctx, id) });
  } catch (error) {
    refused(ctx, `${key}.update`, key, id, error);
    return failure(error);
  }
}

export async function action(request: Request, key: string, id: string, name: string): Promise<Response> {
  let ctx: Ctx | null = null;
  try {
    const def = moduleOf(key);
    const declared = def.actions.find((candidate) => candidate.key === name);
    if (!declared) throw new HttpError(404, 'notFound');
    ctx = await authorizeApi(request, def.key, declared.grant);
    const body = await readBody(request);
    const values = declared.fields ? parseBody(declared.fields, body) : {};
    const current = ctx;
    // The state is read again inside the transaction that changes it, so two
    // clerks pressing the same button cannot both pass the check.
    tx(() => {
      const row: Row = findRecord(def, current, id);
      if (!declared.when(row, current)) throw new HttpError(409, 'state');
      declared.run(current, row, values);
    });
    audit({ accountId: ctx.account.id, role: ctx.role, action: `${def.key}.${name}`, module: def.key, record: id, outcome: 'allowed', status: 200, address: ctx.address });
    return Response.json({ ok: true, item: findRecord(def, ctx, id) });
  } catch (error) {
    refused(ctx, `${key}.${name}`, key, id, error);
    return failure(error);
  }
}

function csvCell(value: unknown): string {
  if (value === null || value === undefined) return '';
  let text = String(value);
  // A cell a spreadsheet would evaluate as a formula is neutralised.
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

// An export is an action like any other: a grant, a row limit, the current
// filters and the same record scope as the list, and an audit entry.
export async function exportCsv(request: Request, key: string): Promise<Response> {
  try {
    const def = moduleOf(key);
    const ctx = await authorizeApi(request, def.key, 'export');
    const query = readQuery(def, new URL(request.url).searchParams);
    const result = runList(def, ctx, query, EXPORT_LIMIT);
    const labels = ctx.config.modules[def.key].columns;
    const lines = [def.columns.map((column) => csvCell(labels[column.key] ?? column.key)).join(',')];
    for (const item of result.items) lines.push(def.columns.map((column) => csvCell(item[column.key])).join(','));
    audit({ accountId: ctx.account.id, role: ctx.role, action: `${def.key}.export`, module: def.key, record: `${result.items.length} rows`, outcome: 'allowed', status: 200, address: ctx.address });
    return new Response(`${lines.join('\n')}\n`, {
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${def.key}-${ctx.today}.csv"`,
      },
    });
  } catch (error) {
    return failure(error);
  }
}

export function isModule(key: string): key is ModuleKey {
  return key in MODULES;
}
